# Generated by Django 5.1.15 on 2026-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('safety_officer', 'Safety Officer'), ('analyst', 'Analyst'), ('viewer', 'Viewer'), ('admin_flow', 'Admin Flow')], default='viewer', help_text='Determines what the user can see and do in the platform.', max_length=20),
        ),
    ]
