# Generated by Django 5.1.15 on 2026-08-31 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='The incident ID from the source EHS system, if present.', max_length=255, null=True)),
                ('incident_date', models.DateField(blank=True, db_index=True, help_text='Date the incident occurred.', null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_task', models.CharField(blank=True, help_text='Job task or activity being performed at the time of the incident.', max_length=255, null=True)),
                ('equipment_involved', models.CharField(blank=True, max_length=255, null=True)),
                ('injury_type', models.CharField(blank=True, max_length=255, null=True)),
                ('body_part', models.CharField(blank=True, max_length=255, null=True)),
                ('immediate_cause', models.CharField(blank=True, max_length=255, null=True)),
                ('root_cause_category', models.CharField(blank=True, max_length=255, null=True)),
                ('severity_actual', models.CharField(blank=True, choices=[('none', 'No Injury / Near Miss'), ('first_aid', 'First Aid'), ('medical_treatment', 'Medical Treatment'), ('lost_time', 'Lost Time Injury'), ('fatality', 'Fatality')], db_index=True, help_text='Recorded outcome severity.', max_length=30, null=True)),
                ('severity_potential', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('fatality', 'Fatality')], db_index=True, help_text="Safety officer's assessed potential severity.", max_length=30, null=True)),
                ('near_miss', models.BooleanField(blank=True, help_text='True if this was classified as a near-miss event.', null=True)),
                ('description', models.TextField(blank=True, help_text='Main incident narrative / description.', null=True)),
                ('corrective_actions', models.TextField(blank=True, help_text='Corrective / preventive actions taken or planned.', null=True)),
                ('witness_statement', models.TextField(blank=True, help_text='Witness statement(s), if captured.', null=True)),
                ('composite_narrative', models.TextField(blank=True, help_text='Cleaned and combined text from all free-text fields, used as the input to the BERT encoder.  Generated at ingestion time. NOTE: BERT (distilbert-base-uncased) truncates at 512 tokens — very long narratives will be truncated.  A sliding-window or summarisation approach is a documented future improvement.', null=True)),
                ('raw_row', models.JSONField(blank=True, default=dict, help_text='The original source row exactly as it arrived, before any mapping or cleaning.  Stored verbatim for traceability and audit.')),
                ('is_psif_human_label', models.BooleanField(blank=True, help_text='[GROUND TRUTH] A safety professional has reviewed this incident and explicitly confirmed (True) or denied (False) that it is a PSIF. May be shown in the UI without qualification.', null=True)),
                ('is_psif_heuristic_label', models.BooleanField(blank=True, help_text="[TRAINING ONLY — NOT GROUND TRUTH] Automatically derived: severity_potential ∈ {serious, fatality} AND severity_actual ∈ {none, first_aid, medical_treatment}. Must NEVER be shown in the UI without clearly marking it as 'estimated from severity fields'.", null=True)),
                ('psif_label_source', models.CharField(choices=[('human', 'Human Reviewed'), ('heuristic', 'Estimated from Severity Fields'), ('none', 'No Label Available')], db_index=True, default='none', help_text='Indicates the origin and reliability of the PSIF label on this incident.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dataset', models.ForeignKey(blank=True, help_text='Source dataset, if this incident was uploaded as part of a batch. Null for manually-entered single incidents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'ordering': ['-incident_date', '-created_at'],
                'indexes': [models.Index(fields=['department', 'incident_date'], name='incidents_i_departm_05fc0f_idx'), models.Index(fields=['severity_actual', 'severity_potential'], name='incidents_i_severit_e62fcb_idx')],
            },
        ),
    ]
