# Generated by Django 5.1.15 on 2026-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed_psif', 'Reviewed (PSIF)'), ('reviewed_non_psif', 'Reviewed (Non-PSIF)')], db_index=True, default='pending', max_length=20),
        ),
    ]
