# Generated by Django 5.1.15 on 2026-09-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOGPRuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(help_text='The matched IOGP Rule name.', max_length=100)),
                ('matched_keywords', models.JSONField(default=list, help_text='List of phrases or keywords that triggered the rule match.')),
                ('matched_fields', models.JSONField(default=list, help_text='List of incident fields that contained the triggering evidence.')),
                ('classification_method', models.CharField(default='rule_based', help_text='Method used for classification (e.g., rule_based).', max_length=50)),
                ('classifier_version', models.CharField(default='iogp_rules_v1', help_text='Version of the taxonomy/classifier ruleset.', max_length=50)),
                ('confidence', models.FloatField(default=1.0, help_text='Heuristic match score. Not a statistical probability.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(help_text='The incident this rule tag applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='iogp_rules', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'IOGP Rule Tag',
                'verbose_name_plural': 'IOGP Rule Tags',
                'constraints': [models.UniqueConstraint(fields=('incident', 'rule', 'classifier_version'), name='unique_incident_iogp_rule')],
            },
        ),
    ]
