# Generated by Django 5.1.15 on 2026-09-02 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_iogpruletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='The dense float array representing the text embedding.')),
                ('embedding_model', models.CharField(help_text='The model used to generate the embedding (e.g., distilbert-base-uncased).', max_length=100)),
                ('embedding_version', models.CharField(default='v1', help_text='Version identifier for the embedding methodology.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(help_text='The incident this embedding represents.', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Embedding',
                'verbose_name_plural': 'Incident Embeddings',
            },
        ),
    ]
