# Generated by Django 5.1.15 on 2026-09-02 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidentembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDataQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='VALID', help_text='The overall data quality status.', max_length=20)),
                ('findings', models.JSONField(default=list, help_text='List of structured findings.')),
                ('quality_version', models.CharField(default='incident_quality_v1', help_text='Version of the data quality ruleset.', max_length=50)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(help_text='The incident this data quality check applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='data_quality', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Data Quality',
                'verbose_name_plural': 'Incident Data Quality Checks',
            },
        ),
    ]
