# Generated by Django 5.1.15 on 2026-09-04 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentdataquality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the human PSIF review was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The user who submitted the human PSIF review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='reviewer_rationale',
            field=models.TextField(blank=True, default='', help_text="Reviewer's written justification for the human PSIF label. Required when the human label overrides a prior heuristic/AI call."),
        ),
    ]
