# Generated by Django 5.1.15 on 2026-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_add_human_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='control_condition',
            field=models.CharField(blank=True, choices=[('effective', 'Effective / Held'), ('failed', 'Failed'), ('absent', 'Absent / Not Implemented'), ('bypassed', 'Bypassed / Defeated'), ('unknown', 'Unknown / Not Determined')], default='unknown', help_text='Condition or performance of the control (effective, failed, absent, bypassed, unknown).', max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='control_failed_bypassed',
            field=models.BooleanField(blank=True, help_text='True if direct control condition was failed or bypassed.', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='control_type',
            field=models.CharField(blank=True, choices=[('loto_isolation', 'LOTO / Energy Isolation (Direct)'), ('machine_guarding', 'Machine Guarding / Interlocks (Direct)'), ('physical_barrier', 'Physical Barrier / Exclusion Zone (Direct)'), ('fall_protection', 'Fall Protection / Harness / Railing (Direct)'), ('permit_isolation', 'Permit-Based Isolation / Hot Work Control (Direct)'), ('ventilation_monitoring', 'Ventilation / Atmospheric Monitoring (Direct)'), ('training', 'Training / Competency (Indirect)'), ('signage', 'Signage / Warnings (Indirect)'), ('ppe', 'Personal Protective Equipment (Indirect)'), ('rules_procedures', 'Rules / Safe Working Procedures (Indirect)'), ('supervision', 'Supervision / Experience (Indirect)'), ('other', 'Other Control'), ('unknown', 'Unknown / Not Determined')], default='unknown', help_text='Primary control type in place or required.', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='direct_control_present',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown / Not Determined')], default='unknown', help_text='Whether a direct control was present to mitigate the high-energy hazard.', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='energy_type',
            field=models.CharField(blank=True, choices=[('gravity_height', 'Gravity / Working at Height'), ('electrical', 'Electrical'), ('mechanical_motion', 'Mechanical Motion / Rotating Equipment'), ('pressure', 'Pressure / Stored Energy'), ('chemical', 'Chemical / Toxic / Flammable'), ('thermal', 'Thermal (Extreme Heat/Cold)'), ('radiation', 'Radiation'), ('sound', 'Sound / Noise'), ('motor_vehicle', 'Motor Vehicle / Driving'), ('other', 'Other'), ('unknown', 'Unknown / Not Determined')], default='unknown', help_text='Type of energy involved in the event or hazard.', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='high_energy_present',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown / Not Determined')], default='unknown', help_text='Presence of high energy hazard (gravity/height, pressure, electrical, etc.).', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='report_type',
            field=models.CharField(blank=True, choices=[('unsafe_act', 'Unsafe Act'), ('unsafe_condition', 'Unsafe Condition'), ('near_miss', 'Near Miss'), ('incident', 'Incident / Event')], db_index=True, help_text='Classification of the report (unsafe act, unsafe condition, near miss, incident).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='worker_exposed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown / Not Determined')], default='unknown', help_text='Whether a worker was in the line of fire or exposed to the energy source.', max_length=10),
        ),
    ]
