# Generated by Django 5.1.15 on 2026-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incident_control_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reviewer_rationale',
            field=models.TextField(blank=True, help_text="Reviewer's written justification for the human PSIF label. Required when the human label overrides a prior heuristic/AI call.", null=True),
        ),
    ]
