# Generated by Django 5.1.15 on 2026-09-05 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_incident_reviewer_rationale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='adjudicated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when final adjudication was recorded.', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='adjudicated_by',
            field=models.ForeignKey(blank=True, help_text='The HSE lead/auditor who performed or finalized adjudication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudicated_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='adjudicated_human_decision',
            field=models.CharField(blank=True, choices=[('PSIF', 'PSIF'), ('NOT_PSIF', 'NOT PSIF'), ('INSUFFICIENT_INFORMATION', 'Insufficient Information')], db_index=True, help_text='Adjudicated human consensus label (PSIF, NOT PSIF, or INSUFFICIENT INFORMATION).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='adjudication_rationale',
            field=models.TextField(blank=True, help_text='Formal HSE adjudication rationale resolving reviewer consensus or overrides.', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='adjudication_status',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('UNDER_REVIEW', 'Under Review'), ('ADJUDICATED', 'Adjudicated')], db_index=True, default='UNREVIEWED', help_text='Status of human expert review and consensus adjudication.', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('PSIF', 'PSIF'), ('NOT_PSIF', 'NOT PSIF'), ('INSUFFICIENT_INFORMATION', 'Insufficient Information')], help_text="Reviewer's domain classification (PSIF, NOT PSIF, or INSUFFICIENT INFORMATION).", max_length=30)),
                ('rationale', models.TextField(blank=True, default='', help_text="Reviewer's written domain reasoning explaining the decision.")),
                ('rubric_version', models.CharField(default='1.0', help_text='Version of the HSE rubric used during evaluation.', max_length=20)),
                ('rubric_answers', models.JSONField(blank=True, default=dict, help_text='Structured answers to rubric criteria (A: hazard, B: exposure, C: control, D: consequence, E: escalation, F: sufficiency).')),
                ('was_blinded', models.BooleanField(default=True, help_text='True if the review was performed blinded (without viewing model prediction or score).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(help_text='The incident evaluated by the reviewer.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='incidents.incident')),
                ('reviewer', models.ForeignKey(blank=True, help_text='The HSE expert who submitted this review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reviews_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incident review',
                'verbose_name_plural': 'incident reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', 'reviewer'], name='incidents_i_inciden_f0c8fa_idx'), models.Index(fields=['decision'], name='incidents_i_decisio_f4e2d0_idx'), models.Index(fields=['created_at'], name='incidents_i_created_17877e_idx')],
            },
        ),
    ]
