# Generated by Django 5.1.15 on 2026-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incident_adjudicated_at_incident_adjudicated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_synthetic_adjudication',
            field=models.BooleanField(db_index=True, default=False, help_text='True if adjudication was performed by an automated simulation/evaluation script rather than a genuine human HSE expert.'),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='is_synthetic',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this review was generated by an automated simulation/evaluation script rather than a genuine human HSE expert.'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_psif_heuristic_label',
            field=models.BooleanField(blank=True, help_text='[HISTORICAL AUDIT / WEAK LABEL] Automatically derived heuristic label from severity fields. Preserved for provenance and baseline comparison. Superseded by adjudicated_human_decision.', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_psif_human_label',
            field=models.BooleanField(blank=True, help_text='[BACKWARD COMPATIBILITY] Binary boolean projection of adjudicated_human_decision (True for PSIF, False for NOT_PSIF, None for unreviewed or INSUFFICIENT_INFORMATION). Authoritative multi-reviewer decisions reside in IncidentReview and adjudicated_human_decision.', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='psif_label_source',
            field=models.CharField(choices=[('human', 'Human Reviewed'), ('heuristic', 'Estimated from Severity Fields'), ('synthetic', 'Synthetic Evaluation Simulation'), ('none', 'No Label Available')], db_index=True, default='none', help_text='Indicates the origin and reliability of the PSIF label on this incident.', max_length=20),
        ),
    ]
