# Generated by Django 5.1.15 on 2026-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_remove_incident_is_psif_heuristic_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reviewer_rationale',
            field=models.TextField(blank=True, help_text='Required when the human label overrides a prior model prediction or when confirming high-consequence edge cases.', null=True),
        ),
        migrations.AlterField(
            model_name='iogpruletag',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='Keyword rule match score. Not a statistical probability.'),
        ),
    ]
