# Generated by Django 5.1.15 on 2026-09-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_alter_incident_reviewer_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreview',
            name='action_library_version',
            field=models.CharField(blank=True, default='action_library_v1', help_text='Version of the Action Engine library.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='agreement_state',
            field=models.CharField(blank=True, help_text='Computed agreement state: AGREEMENT, HUMAN_OVERRIDES_MODEL, HUMAN_OVERRIDES_RULE, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='evidence_notes',
            field=models.TextField(blank=True, default='', help_text='Reviewer observational notes, disagreement justification, or field findings.'),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='knowledge_base_version',
            field=models.CharField(blank=True, default='psif_kb_v1.0', help_text='Version of the PSIF knowledge base.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='model_version',
            field=models.CharField(blank=True, help_text='Active ML model version at time of review.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='previous_decision',
            field=models.CharField(blank=True, choices=[('PSIF', 'PSIF'), ('NOT_PSIF', 'NOT PSIF'), ('INSUFFICIENT_INFORMATION', 'Insufficient Information')], help_text='Previous decision if this review represents an edit or amendment.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='reasoning_ruleset_version',
            field=models.CharField(blank=True, default='psif_ruleset_v1.0', help_text='Version of the safety reasoning ruleset.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='review_provenance',
            field=models.CharField(default='HUMAN_EXPERT', help_text='Provenance of the review: HUMAN_EXPERT, SYNTHETIC_SIMULATED, HISTORICAL_AUDIT.', max_length=50),
        ),
        migrations.AddField(
            model_name='incidentreview',
            name='structured_evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Structured answers for hazard, exposure, control, consequence, missing evidence, IOGP rule.'),
        ),
    ]
