# Generated by Django 5.1.15 on 2026-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_incidentreview_action_library_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Workspace isolation identifier. NULL for existing global dataset; 'admin_flow' for Admin Flow demo.", max_length=50, null=True),
        ),
    ]
