# Generated by Django 5.2.15 on 2026-09-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_site_per_organization',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='barrier_failures',
            new_name='evidence_data',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='uploaded_file',
            new_name='source_file',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='narrative',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='reviewer_verdict',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('organization', 'name')},
        ),
        migrations.AddField(
            model_name='prediction',
            name='classification',
            field=models.CharField(default='NON-SIF', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='precursor_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='prediction',
            name='risk_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='life_saving_rule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='activity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='site',
            name='created_at',
        ),
    ]
