# Generated by Django 5.2.17 on 2026-09-02 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_site_unique_site_per_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='submitted_by',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='precursor_data',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity',
        ),
        migrations.AddField(
            model_name='report',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
