# Generated by Django 5.2.17 on 2026-09-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_submitted_by_report_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('classification', models.CharField(max_length=50)),
                ('is_sif', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('sif_probability', models.FloatField(default=0.0)),
                ('non_sif_probability', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='LOW', max_length=50)),
                ('life_saving_rule', models.CharField(blank=True, default='Unclassified', max_length=150)),
                ('precursors', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('barrier_failures', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True, default='')),
                ('potential_consequence', models.TextField(blank=True, default='')),
                ('recommended_measures', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
