# Generated by Django 5.2.17 on 2026-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_safetyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='activity',
            field=models.CharField(blank=True, default='General Operations', max_length=150),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='activity_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='lsr_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='lsr_source',
            field=models.CharField(default='ml', max_length=20),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='site_area',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
